name: Daily Job
on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        run: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Visit camel
        run: node index.js
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EGYSZAM: ${{ secrets.EGYSZAM }}
          RANDOM_UPTO: ${{ secrets.RANDOM_UPTO }}