name: Daily Job
on:
  schedule:
    - cron: '30 6 * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install Node.js
        run: apk add --no-cache nodejs npm
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Visit camel
        run: node index.js
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EGYSZAM: ${{ secrets.EGYSZAM }}
          RANDOM_UPTO: ${{ secrets.RANDOM_UPTO }}